### ISSUE TITLE
Make tests work in docker

### ISSUE THREAD

**Issue by muan** [muan/emoji-cli#1]
This is what I've got so far: https://github.com/muan/emoji-cli/compare/tests, and here's what I want to do:
1. `$ docker-compose run bintest`
2. `Dockerfile-test` installs `xclip`, sets up `Xvfb` so I have a display for `xclip`.
3. Test calls `emoji-cli poop` and script copies 💩 to the clipboard.<< Not working
4. Verify CLI output matches & clipboard content (`xclip -o`) matches

My futile attempts led me here opening an issue wishing I can source help from people who are more experienced in Docker than myself while documenting this of my own sanity. (my experience with docker dates back to the day I started this project. :joy:)

I have tried many many things including CMD in docker compose file w/ `bash -c`, shelling the `Xvfb` command from the `bintest` rake task, and using `xvfb-run -a xclip`<sup>[1](#user-content-yolo)</sup> which led me me to more errors which I then failed to solve... :bow:

When running these in `docker-compose run shell` the command just hangs and errors out with `XSELINUXs still allocated at reset`:

``` shell
$ Xvfb :1 &
$ ./mruby/build/x86_64-pc-linux-gnu/bin/emoji-cli poop
```

``` shell
# while this totes works right after
$ echo 'hello' | xclip -i
$ xclip -o
hello

```

Ugh. I think I just need to stop now and reconvene in the future.

![a cat having no idea what it's doing](https://cloud.githubusercontent.com/assets/1153134/11868101/dcec08ae-a4f8-11e5-8fab-420e6545852a.png)

---

1.
<a name="yolo"></a>

```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":99"
      after 10 requests (7 known processed) with 0 events remaining.
```

**Comment by audreyt** [comment]
I have no idea what I'm doing either, but https://github.com/muan/emoji-cli/pull/2 seems to work. Enjoy!
